In [1]:
import numpy as np
# 1
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [2]:
# 2
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 3
a.shape

(3, 5)

In [4]:
# 4
a.ndim

2

In [5]:
#5
a.dtype.name

'int32'

In [6]:
#6
a.dtype

dtype('int32')

In [7]:
#7
a.size

15

In [8]:
#8
type(a)

numpy.ndarray

In [9]:
#9
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [12]:
#10
b = np.append(a,2)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  2])

In [17]:
#11
b.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 2]

In [30]:
#12
c = np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [19]:
#13
d = np.ones(5)
d

array([1., 1., 1., 1., 1.])

In [20]:
#14
np.concatenate((d,c), axis = 0)

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [21]:
#15
np.multiply(c,d)

array([0., 0., 0., 0., 0.])

In [22]:
#16
np.divide(c,d)

array([0., 0., 0., 0., 0.])

In [23]:
#17
np.power(d,c)

array([1., 1., 1., 1., 1.])

In [24]:
#18
np.subtract(c,d)

array([-1., -1., -1., -1., -1.])

In [25]:
#19
np.add(c,d)

array([1., 1., 1., 1., 1.])

In [28]:
#20
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [26]:
#21
np.full((4,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [29]:
#22
np.array_equal(a,a)

True

In [31]:
#23
np.sqrt(c)

array([0., 0., 0., 0., 0.])

In [35]:
#24
e = np.sin(d)
e

array([0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098])

In [33]:
#25
np.log(d)

array([0., 0., 0., 0., 0.])

In [34]:
#26
np.abs(-d)

array([1., 1., 1., 1., 1.])

In [36]:
#27
np.ceil(e)

array([1., 1., 1., 1., 1.])

In [38]:
#28
np.floor(e)

array([0., 0., 0., 0., 0.])

In [39]:
#29
np.round(e)

array([1., 1., 1., 1., 1.])

In [40]:
#30
print(np.__version__)

1.19.4


In [42]:
#31, boolean array
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [43]:
#32
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [45]:
#33
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [46]:
# 34, where Odd replace by -1 in arr
np.where(arr % 2 == 1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [47]:
#35, stack one upon another
np.vstack([c,d])

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [48]:
#36, join horizontally
np.r_[c,d]

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [54]:
#37, stack end to end
np.hstack([c,d])

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [55]:
#38, ****************
np.c_[c,d]

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [53]:
#39
np.repeat(4,10)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [57]:
#40, repeats array and joins
np.tile(c,2)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
#41, common amid 2 arrays is returned
np.intersect1d(c,d)

array([], dtype=float64)

In [59]:
#42, remove array d elements from c and returns modified c
np.setdiff1d(c,d)

array([0.])

In [60]:
#43, all items between 5 and 10
np.where((a >= 5) & (a <= 10))

(array([1, 1, 1, 1, 1, 2], dtype=int32),
 array([0, 1, 2, 3, 4, 0], dtype=int32))

In [61]:
#44
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [63]:
#45
np.random.rand(2,3)

array([[0.96618317, 0.71902684, 0.19633743],
       [0.85760772, 0.32719008, 0.05979055]])

In [68]:
#46
np.random.randint(2,10)

6

In [69]:
#47
e.copy()

array([0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098])

In [70]:
#48
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
#49, split array in 3 rows
np.split(a,3)

[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]])]

In [72]:
#50
np.delete(a,3, axis = 1)

array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  9],
       [10, 11, 12, 14]])