In [2]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
a.shape

(3, 5)

In [9]:
a.ndim

2

In [10]:
a.dtype.name

'int32'

In [15]:
a.dtype

dtype('int32')

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [13]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [27]:
b = np.append(,2)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  2])

In [28]:
b.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 2]

In [33]:
c = np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [35]:
d = np.ones(5)
d

array([1., 1., 1., 1., 1.])

In [41]:
np.concatenate((d,c), axis = 0)

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [42]:
np.multiply(c,d)

array([0., 0., 0., 0., 0.])

In [43]:
np.divide(c,d)

array([0., 0., 0., 0., 0.])

In [44]:
np.power(d,c)

array([1., 1., 1., 1., 1.])

In [45]:
np.subtract(c,d)

array([-1., -1., -1., -1., -1.])

In [46]:
np.add(c,d)

array([1., 1., 1., 1., 1.])

In [48]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [50]:
np.full((4,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])